"""app notifications

Revision ID: 81b6c2ed8d4b
Revises: 08678a1ce6ad
Create Date: 2026-07-15 15:04:22.059084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81b6c2ed8d4b"
down_revision: Union[str, Sequence[str], None] = "08678a1ce6ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

create_trigger = """
    CREATE TRIGGER trig_{table}_updated BEFORE UPDATE ON {schema}.{table}
    FOR EACH ROW EXECUTE PROCEDURE {schema}.refresh_updated_at();
    """


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("POST", "COMMENT", "LIKE", "DM", "FOLLOW", name="notificationkind"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("receiver_id", sa.Integer(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["receiver_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(sa.text(create_trigger.format(table="app_notification", schema="public")))
    op.create_index(
        "uix_author_event_resource",
        "app_notification",
        ["event_type", "author_id", "resource_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_author_event_resource", table_name="app_notification")
    op.drop_table("app_notification")
    # ### end Alembic commands ###
