"""user blocking user following

Revision ID: b67e4f2a989b
Revises: 4b2be440ac05
Create Date: 2026-07-13 19:54:50.919772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b67e4f2a989b"
down_revision: Union[str, Sequence[str], None] = "4b2be440ac05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

create_trigger = """
    CREATE TRIGGER trig_{table}_updated BEFORE UPDATE ON {schema}.{table}
    FOR EACH ROW EXECUTE PROCEDURE {schema}.refresh_updated_at();
    """

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_blocked",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blocking_user_id", sa.Integer(), nullable=False),
        sa.Column("blocked_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["blocked_by_user_id"], ["users.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["blocking_user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uix_blocking_blocked_users",
        "users_blocked",
        ["blocking_user_id", "blocked_by_user_id"],
        unique=True,
    )
    op.execute(sa.text(create_trigger.format(table="users_blocked", schema="public")))
    op.create_table(
        "users_following",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("following_user_id", sa.Integer(), nullable=False),
        sa.Column("follower_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["follower_user_id"], ["users.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["following_user_id"], ["users.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uix_following_follower_users",
        "users_following",
        ["following_user_id", "follower_user_id"],
        unique=True,
    )
    op.execute(sa.text(create_trigger.format(table="users_following", schema="public")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_following_followe_users", table_name="users_following")
    op.drop_table("users_following")
    op.drop_index("uix_blocking_blocked_users", table_name="users_blocked")
    op.drop_table("users_blocked")
    # ### end Alembic commands ###
