"""post likes comments

Revision ID: 4b2be440ac05
Revises: 47a34f34921f
Create Date: 2026-07-11 14:16:06.290483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b2be440ac05"
down_revision: Union[str, Sequence[str], None] = "47a34f34921f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

create_trigger = """
    CREATE TRIGGER trig_{table}_updated BEFORE UPDATE ON {schema}.{table}
    FOR EACH ROW EXECUTE PROCEDURE {schema}.refresh_updated_at();
    """

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content", sa.VARCHAR(length=256), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("parent_comment_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["parent_comment_id"], ["post_comments.id"]
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_likes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.execute(sa.text(create_trigger.format(table="post_likes", schema="public")))
    op.execute(sa.text(create_trigger.format(table="post_comments", schema="public")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False)
    op.drop_table("post_likes")
    op.drop_table("post_comments")
    # ### end Alembic commands ###
